In [1]:
!conda install numpy

Solving environment: done

# All requested packages already installed.



In [2]:
import numpy as np



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 0  2  4  6  8 10 12 14 16 18 20]
[ 0  3  6  9 12 15 18]


In [3]:
#1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。
a=np.arange(21)
print(a)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
#2.呈上題，將以上數列取出偶數。
b=slice(0,21,2)
print(a[b])


In [ ]:
#3.呈1題，將數列取出3的倍數。
c=slice(0,21,3)
print(a[c])